# Generated by Django 3.0.1 on 2020-01-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('MN_Id_Menu', models.BigAutoField(primary_key=True, serialize=False)),
                ('MN_Nombre_Menu', models.CharField(max_length=50)),
                ('MN_Url_Menu', models.CharField(max_length=30)),
                ('MN_Icono_Menu', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'TBL_Menus',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('PRM_Id_Permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('PRM_Nombre_Permiso', models.CharField(max_length=50)),
                ('PRM_Slug_Permiso', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TBL_Permisos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('RLS_Id_Rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('RLS_Nombre_Rol', models.CharField(max_length=30)),
                ('RLS_Descripcion_Rol', models.TextField()),
            ],
            options={
                'db_table': 'TBL_Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('USR_Id_Usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('USR_Tipo_Documento_Usuario', models.CharField(max_length=30)),
                ('USR_Documento_Usuario', models.CharField(max_length=50)),
                ('USR_Nombres_Usuario', models.CharField(max_length=50)),
                ('USR_Apellidos_Usuario', models.CharField(max_length=50)),
                ('USR_Direccion_Usuario', models.CharField(max_length=50)),
                ('USR_Telenofo_Usuario', models.CharField(max_length=12)),
                ('USR_Email_Usuario', models.EmailField(max_length=254)),
                ('USR_Nombre_Usuario', models.CharField(max_length=15)),
                ('USR_Contrasena_Usuario', models.TextField()),
            ],
            options={
                'db_table': 'TBL_Usuarios',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('USR_RLS_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('USR_RLS_Rol_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Usuarios_Roles_Rol_Id', to='Administrador.Rol')),
                ('USR_RLS_Usuario_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Usuarios_Roles_Usuario_Id', to='Administrador.Usuario')),
            ],
            options={
                'db_table': 'TBL_Usuarios_Roles',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPermiso',
            fields=[
                ('USR_PRM_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('USR_PRM_Permiso_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Usuarios_Permisos_Permiso_Id', to='Administrador.Permiso')),
                ('USR_PRM_Usuario_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Usuarios_Permisos_Usuario_Id', to='Administrador.Usuario')),
            ],
            options={
                'db_table': 'TBL_Usuarios_Permisos',
            },
        ),
        migrations.CreateModel(
            name='MenuUsuario',
            fields=[
                ('MN_USR_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('MN_USR_Menu_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Menus_Usuarios_Menu_Id', to='Administrador.Menu')),
                ('MN_USR_Usuario_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Menus_Usuarios_Usuario_Id', to='Administrador.Usuario')),
            ],
            options={
                'db_table': 'TBL_Menus_Usuarios',
            },
        ),
    ]
