# Generated by Django 2.1.7 on 2020-01-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProcesoCompra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('CNT_Id_Contenido', models.BigAutoField(primary_key=True, serialize=False)),
                ('CNT_Nombre_Contenido', models.CharField(max_length=150)),
                ('CNT_Relevancia_Formato', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CNT_Embudo_Formato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Contenidos_Embudo_Id', to='ProcesoCompra.Embudo')),
                ('CNT_Estado_Formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Contenidos_Estado_Id', to='ProcesoCompra.Estado')),
            ],
            options={
                'db_table': 'TBL_Contenidos',
            },
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('FMT_Id_Formato', models.BigAutoField(primary_key=True, serialize=False)),
                ('FMT_Nombre_Formato', models.CharField(max_length=150)),
                ('FMT_Descripcion_Formato', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TBL_Formatos',
            },
        ),
        migrations.AddField(
            model_name='contenido',
            name='CNT_Formato_Contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Contenidos_Formato_Id', to='ListaContenidos.Formato'),
        ),
    ]
