# Generated by Django 3.0.1 on 2020-01-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProcesoCompra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('FMT_Id_Formato', models.BigAutoField(primary_key=True, serialize=False)),
                ('FMT_Nombre_Formato', models.CharField(max_length=150)),
                ('FMT_Descripcion_Formato', models.TextField()),
            ],
            options={
                'db_table': 'TBL_Formatos',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('CNT_Id_Contenido', models.BigAutoField(primary_key=True, serialize=False)),
                ('CNT_Nombre_Contenido', models.CharField(max_length=150)),
                ('CNT_Relevancia_Formato', models.CharField(max_length=20)),
                ('CNT_Embudo_Formato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Contenidos_Embudo_Id', to='ProcesoCompra.Embudo')),
                ('CNT_Estado_Formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Contenidos_Estado_Id', to='ProcesoCompra.Estado')),
                ('CNT_Formato_Contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Contenidos_Formato_Id', to='ListaContenidos.Formato')),
            ],
            options={
                'db_table': 'TBL_Contenidos',
            },
        ),
    ]
