# Generated by Django 3.0.1 on 2020-01-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('EST_Id_Estado', models.BigAutoField(primary_key=True, serialize=False)),
                ('EST_Nombre_Estado', models.CharField(max_length=100)),
                ('EST_Descripcion_Estado', models.TextField()),
            ],
            options={
                'db_table': 'TBL_Estados',
            },
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('IDA_Id_Idea', models.BigAutoField(primary_key=True, serialize=False)),
                ('IDA_Descripcion_Idea', models.TextField()),
            ],
            options={
                'db_table': 'TBL_Ideas',
            },
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('ETP_Id_Etapa', models.BigAutoField(primary_key=True, serialize=False)),
                ('ETP_Descripcion_Etapa', models.TextField()),
                ('ETP_Estado_Etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Etapas_Estado_Id', to='ProcesoCompra.Estados')),
                ('ETP_Idea_Etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Etapas_Idea_Id', to='ProcesoCompra.Ideas')),
            ],
            options={
                'db_table': 'TBL_Etapas',
            },
        ),
        migrations.CreateModel(
            name='Embudo',
            fields=[
                ('EBD_Id_Embudo', models.BigAutoField(primary_key=True, serialize=False)),
                ('EBD_Etapa_Embudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Embudo_Etapa_Id', to='ProcesoCompra.Etapas')),
                ('EBD_Persona_Embudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Embudo_Persona_Id', to='Persona.Personas')),
            ],
            options={
                'db_table': 'TBL_Embudo',
            },
        ),
    ]
