# Generated by Django 2.1.7 on 2020-01-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProcesoCompra', '0001_initial'),
        ('ListaContenidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('CMP_Id_Campana', models.BigAutoField(primary_key=True, serialize=False)),
                ('CMP_Nombre_Campana', models.CharField(max_length=150)),
                ('CMP_Fecha_Campana', models.DateField()),
                ('CMP_Horario_Campana', models.TimeField()),
                ('CMP_Frecuencia_Campana', models.CharField(max_length=50)),
                ('CMP_Archivo_Campana', models.TextField()),
                ('CMP_Contenido_Campana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Campanas_Contenido_Id', to='ListaContenidos.Contenido')),
                ('CMP_Estado_Campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Campanas_Estado_Id', to='ProcesoCompra.Estado')),
            ],
            options={
                'db_table': 'TBL_Campanas',
            },
        ),
        migrations.CreateModel(
            name='TipoCampana',
            fields=[
                ('TCM_Id_Tipo_Campana', models.BigAutoField(primary_key=True, serialize=False)),
                ('TCM_Nombre_Tipo_Campana', models.CharField(max_length=150)),
                ('TCM_Descripcion_Campana', models.TextField()),
            ],
            options={
                'db_table': 'TBL_Tipo_Campana',
            },
        ),
        migrations.AddField(
            model_name='campana',
            name='CMP_Tipo_Campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Campanas_Tipo_Campana_Id', to='PlanificacionEmails.TipoCampana'),
        ),
    ]
