# Generated by Django 2.1.7 on 2020-01-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comportamiento',
            fields=[
                ('CMP_Id_Comportamiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('CMP_Descripcion_Comportamiento', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TBL_Comportamientos',
            },
        ),
        migrations.CreateModel(
            name='ComportamientoMedio',
            fields=[
                ('CMP_MDO_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CMP_MDO_Comportamiento_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Comportamientos_Medios_Comportamiento_Id', to='Persona.Comportamiento')),
            ],
            options={
                'db_table': 'TBL_Comportamientos_Medios',
            },
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('ESC_Id_Escolaridad', models.BigAutoField(primary_key=True, serialize=False)),
                ('ESC_Nombre_Escolaridad', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TBL_Escolaridad',
            },
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('MDO_Id_Medio', models.BigAutoField(primary_key=True, serialize=False)),
                ('MDO_Nombre_Medio', models.CharField(max_length=150)),
                ('MDO_Descripcion_Medio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TBL_Medios',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('OBJ_Id_Objetivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('OBJ_Respuesta_Objetivo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TBL_Objetivos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('PSN_Id_Persona', models.BigAutoField(primary_key=True, serialize=False)),
                ('PSN_Nombres_Persona', models.CharField(max_length=45)),
                ('PSN_Apellidos_Persona', models.CharField(max_length=45)),
                ('PSN_Edad_Persona', models.IntegerField()),
                ('PSN_Sexo_Persona', models.CharField(max_length=25)),
                ('PSN_Cargo_Persona', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('PSN_Escoladidad_Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Persona_Escolaridad_Escolaridad_Id', to='Persona.Escolaridad')),
            ],
            options={
                'db_table': 'TBL_Personas',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('PRG_Id_Pregunta', models.BigAutoField(primary_key=True, serialize=False)),
                ('PRG_Nombre_Pregunta', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TBL_Preguntas',
            },
        ),
        migrations.AddField(
            model_name='objetivo',
            name='OBJ_Persona_Objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Objetivos_Persona_Id', to='Persona.Persona'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='OBJ_Pregunta_Objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Objetivos_Pregunta_Id', to='Persona.Pregunta'),
        ),
        migrations.AddField(
            model_name='comportamientomedio',
            name='CMP_MDO_Medio_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Comportamientos_Medios_Medio_Id', to='Persona.Medio'),
        ),
        migrations.AddField(
            model_name='comportamiento',
            name='CMP_Persona_Comportamiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Comportamiento_Personas_Id', to='Persona.Persona'),
        ),
    ]
