# Generated by Django 2.1.7 on 2020-01-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0003_auto_20200129_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='EMP_Tamano_Empresa',
            field=models.CharField(default=-49, max_length=15),
            preserve_default=False,
        ),
    ]
