# Generated by Django 2.1.7 on 2020-01-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0004_empresa_emp_tamano_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='medio',
            name='MDO_Icono_Medio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
