# Generated by Django 2.1.7 on 2020-01-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embudo',
            fields=[
                ('EBD_Id_Embudo', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TBL_Embudo',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('EST_Id_Estado', models.BigAutoField(primary_key=True, serialize=False)),
                ('EST_Nombre_Estado', models.CharField(max_length=100)),
                ('EST_Descripcion_Estado', models.TextField()),
            ],
            options={
                'db_table': 'TBL_Estados',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('ETP_Id_Etapa', models.BigAutoField(primary_key=True, serialize=False)),
                ('ETP_Descripcion_Etapa', models.TextField()),
                ('ETP_Estado_Etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Etapas_Estado_Id', to='ProcesoCompra.Estado')),
            ],
            options={
                'db_table': 'TBL_Etapas',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('IDA_Id_Idea', models.BigAutoField(primary_key=True, serialize=False)),
                ('IDA_Descripcion_Idea', models.TextField()),
            ],
            options={
                'db_table': 'TBL_Ideas',
            },
        ),
        migrations.AddField(
            model_name='etapa',
            name='ETP_Idea_Etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Etapas_Idea_Id', to='ProcesoCompra.Idea'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='EBD_Etapa_Embudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Embudo_Etapa_Id', to='ProcesoCompra.Etapa'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='EBD_Persona_Embudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Embudo_Persona_Id', to='Persona.Persona'),
        ),
    ]
