# Generated by Django 2.1.7 on 2020-01-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesoCompra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='ETP_Idea_Etapa',
        ),
        migrations.AddField(
            model_name='idea',
            name='IDA_Etapa_Idea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FK_Ideas_Etapa_Id', to='ProcesoCompra.Etapa'),
            preserve_default=False,
        ),
    ]
